/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controllers.PatientController;
import java.awt.Font;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import models.Guardian;
import models.Patient;

/**
 *
 * @author DINHHUNG
 */
public class ManagePatient extends javax.swing.JPanel {

    /**
     * Creates new form ManagePatient
     */
    public ManagePatient() {
        initComponents();
        table.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 24));
        loadGuardiansToCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cccd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bhyt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        createId = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        showTable = new javax.swing.JButton();
        giamHo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        maBn = new javax.swing.JTextField();
        add1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Quản Lí Bệnh Nhân");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("CCCD");

        cccd.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Mã BHYT");

        bhyt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Người Giám Hộ");

        createId.setBackground(new java.awt.Color(204, 204, 255));
        createId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        createId.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        createId.setText("Tạo ID");
        createId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createIdActionPerformed(evt);
            }
        });

        edit.setBackground(new java.awt.Color(204, 204, 255));
        edit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-removebg-preview.png"))); // NOI18N
        edit.setText("Sửa");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(204, 204, 255));
        delete.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tải_xuống-removebg-preview.png"))); // NOI18N
        delete.setText("Xóa");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        showTable.setBackground(new java.awt.Color(204, 204, 255));
        showTable.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        showTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pngtree-display-icon-image_1344444-removebg-preview.png"))); // NOI18N
        showTable.setText("Hiện Thị");
        showTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTableActionPerformed(evt);
            }
        });

        giamHo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        giamHo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Mã Bệnh Nhân");

        maBn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        add1.setBackground(new java.awt.Color(204, 204, 255));
        add1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        add1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        add1.setText("Thêm");
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cccd, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maBn)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createId)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(add1)
                        .addGap(39, 39, 39)
                        .addComponent(edit)
                        .addGap(44, 44, 44)
                        .addComponent(delete))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bhyt, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showTable)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(giamHo, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(17, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cccd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(bhyt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(giamHo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(createId)
                        .addComponent(edit)
                        .addComponent(delete)
                        .addComponent(showTable)
                        .addComponent(jLabel5)
                        .addComponent(add1))
                    .addComponent(maBn))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 255, 204));

        table.setBackground(new java.awt.Color(255, 204, 204));
        table.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Bệnh Nhân", "CCCD", "Tên Bênh Nhân", "Mã BHYT", "Người Giám Hộ"
            }
        ));
        table.setRowHeight(30);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(526, 526, 526)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createIdActionPerformed
        maBn.setText(new PatientController().generatePatientId());
    }//GEN-LAST:event_createIdActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
       String patientId = maBn.getText().trim();
    String idCard = cccd.getText().trim();
    String maBhytValue = bhyt.getText().trim();
    
    // Lấy giá trị từ combo "mã - tên"
    String guardianItem = (String) giamHo.getSelectedItem();
    String guardianId = null;
    if (guardianItem != null && !guardianItem.isEmpty()) {
        guardianId = guardianItem.split(" - ")[0]; // chỉ lấy mã
    }

    // Kiểm tra dữ liệu bắt buộc
    if (patientId.isEmpty() || idCard.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Mã bệnh nhân và CCCD không được để trống!");
        return;
    }

    // Tạo đối tượng Patient
    Patient p = new Patient();
    p.setPatientId(patientId);
    p.setIdCard(idCard);
    p.setMaBhyt(maBhytValue);
    p.setGuardianId(guardianId);

    // Gọi controller update
    PatientController pc = new PatientController();
    boolean success = pc.updatePatient(p);

    if (success) {
        javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật bệnh nhân thành công!");
        showTableActionPerformed(null); // refresh bảng
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
    }
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
      String patientId = maBn.getText().trim();

    if (patientId.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn bệnh nhân để xóa!");
        return;
    }

    int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "Bạn có chắc muốn xóa bệnh nhân này?", 
            "Xác nhận", 
            javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        PatientController pc = new PatientController();
        boolean success = pc.deletePatient(patientId);

        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, "Xóa bệnh nhân thành công!");
            showTableActionPerformed(null); // refresh bảng
            // Xóa dữ liệu trên form
            maBn.setText("");
            cccd.setText("");
            bhyt.setText("");
            giamHo.setSelectedIndex(-1);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Xóa thất bại!");
        }
    }
    }//GEN-LAST:event_deleteActionPerformed

    private void showTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTableActionPerformed
    List<Patient> patients = new PatientController().getAllPatients();

    // Lấy model JTable
    DefaultTableModel model = (DefaultTableModel) table.getModel();
    model.setRowCount(0); // Xóa dữ liệu cũ

    PatientController patientCtrl = new PatientController(); // Controller chứa hàm getGuardianName

    // Đổ dữ liệu vào bảng
    for (Patient p : patients) {
        // Lấy họ tên bệnh nhân từ CCCD
        String hoTen = patientCtrl.searchPatient(p.getPatientId());

        // Lấy tên người giám hộ (nếu có)
        String guardianDisplay = "";
        String guardianId = p.getGuardianId();
        if (guardianId != null && !guardianId.isEmpty()) {
            String guardianName = patientCtrl.getGuardianName(guardianId);
            guardianDisplay = guardianId + " - " + (guardianName != null ? guardianName : "");
        }

        // Thêm dòng vào bảng
        model.addRow(new Object[]{
            p.getPatientId(),   // Mã bệnh nhân
            p.getIdCard(),      // CCCD
            hoTen,              // Họ tên
            p.getMaBhyt(),
            guardianDisplay     // Người giám hộ dạng "mã - tên"
        });
    }
    }//GEN-LAST:event_showTableActionPerformed

    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed
        String patientId = maBn.getText().trim();
    String idCard = cccd.getText().trim();
    String maBhytValue = bhyt.getText().trim();

    // Lấy giá trị từ combo "mã - tên"
    String guardianItem = (String) giamHo.getSelectedItem();
    String guardianId = null;
    if (guardianItem != null && !guardianItem.isEmpty()) {
        guardianId = guardianItem.split(" - ")[0]; // chỉ lấy mã
    }

    // Kiểm tra dữ liệu bắt buộc
    if (idCard.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "CCCD không được để trống!");
        return;
    }

    // Nếu chưa tạo Mã bệnh nhân, tự động tạo
    if (patientId.isEmpty()) {
        patientId = new PatientController().generatePatientId();
        maBn.setText(patientId); // điền vào ô
    }

    // Tạo đối tượng Patient
    Patient p = new Patient();
    p.setPatientId(patientId);
    p.setIdCard(idCard);
    p.setMaBhyt(maBhytValue);
    p.setGuardianId(guardianId);

    // Gọi controller thêm bệnh nhân
    PatientController pc = new PatientController();
    boolean success = pc.addPatient(p);

    if (success) {
        javax.swing.JOptionPane.showMessageDialog(this, "Thêm bệnh nhân thành công!");
        showTableActionPerformed(null); // refresh bảng
        // Xóa dữ liệu cũ trên form
        maBn.setText("");
        cccd.setText("");
        bhyt.setText("");
        giamHo.setSelectedIndex(-1);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Thêm bệnh nhân thất bại!");
    }
    }//GEN-LAST:event_add1ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int selectedRow = table.getSelectedRow();
    if (selectedRow >= 0) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        // Đổ dữ liệu từ JTable về các ô JTextField
        maBn.setText(model.getValueAt(selectedRow, 0).toString()); // Mã bệnh nhân
        cccd.setText(model.getValueAt(selectedRow, 1).toString()); // CCCD
        bhyt.setText(model.getValueAt(selectedRow, 3).toString()); // Mã BHYT

        // Người giám hộ
        String guardianDisplay = model.getValueAt(selectedRow, 4).toString(); // "GH001 - Nguyễn Văn A"

        // Duyệt tất cả item trong combo và chọn đúng item
        for (int i = 0; i < giamHo.getItemCount(); i++) {
            if (giamHo.getItemAt(i).equals(guardianDisplay)) {
                giamHo.setSelectedIndex(i);
                break;
            }
        }
    }
    }//GEN-LAST:event_tableMouseClicked
    public  void loadGuardiansToCombo() {
        // Xóa dữ liệu cũ
        giamHo.removeAllItems();

        // Lấy danh sách người giám hộ
        PatientController pgc = new PatientController();
        for (Guardian g : pgc.getAllGuardians()) {
            giamHo.addItem(g.toString()); // Thêm dạng "mã - tên"
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add1;
    private javax.swing.JTextField bhyt;
    private javax.swing.JTextField cccd;
    private javax.swing.JButton createId;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JComboBox<String> giamHo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField maBn;
    private javax.swing.JButton showTable;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
