/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

/**
 *
 * @author phams
 */

import controllers.PrescriptionController;

import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import models.Prescription;


public class ManagePrescription extends javax.swing.JPanel {

    /**
     * Creates new form ManagePrescription
     */
    
    private PrescriptionController prescriptionController;
    private javax.swing.table.DefaultTableModel tableModel;
    private java.text.SimpleDateFormat df = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
//    Tải (làm mới) toàn bộ dữ liệu lên JTable
    private void loadTableData() {
        tableModel.setRowCount(0); 
        try {
            java.util.List<Prescription> list = prescriptionController.getAllPrescriptions();
            
            for (Prescription p : list) {
                tableModel.addRow(new Object[]{
                    p.getMaHoSo(),
                    p.getMaDon(),
                    df.format(p.getNgayKeDon()),
                    p.getMaBacSi()
                });
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi tải dữ liệu bảng: " + e.getMessage(), "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
// Xóa trắng form và tạo mã đơn mới
    private void clearForm() {
        try {
            txtMaDon.setText(prescriptionController.nextPrescriptionID());
            txtNgayKeDon.setText(df.format(new java.util.Date()));
            if (comboMaHoSo.getItemCount() > 0) {
                comboMaHoSo.setSelectedIndex(0);
            }
            if (comboMaBacSi.getItemCount() > 0) {
                comboMaBacSi.setSelectedIndex(0);
            }
            tblDonThuoc.clearSelection();
            
        } catch (Exception e) {
            txtMaDon.setText("Lỗi tạo mã");
            e.printStackTrace();
        }
    }
    
    private void loadInitialData() {
        try {
            // 1. Tải Mã Đơn và Ngày Kê Đơn (Tạo mới)
            txtMaDon.setText(prescriptionController.nextPrescriptionID());
            txtNgayKeDon.setText(df.format(new java.util.Date()));
            txtNgayKeDon.setEditable(false); // Không cho sửa
            
            // 2. Tải Mã Hồ Sơ (LẤY CÓ SẴN)
            List<String> recordIDs = prescriptionController.getAllMedicalRecordIDs();
            comboMaHoSo.removeAllItems(); // Xóa các mục cũ
            for (String id : recordIDs) {
                comboMaHoSo.addItem(id);
            }
            
            // 3. Tải Mã Bác Sĩ (LẤY CÓ SẴN)
            List<String> doctorIDs = prescriptionController.getAllDoctorIDs();
            comboMaBacSi.removeAllItems(); // Xóa các mục cũ
            for (String id : doctorIDs) {
                comboMaBacSi.addItem(id);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            // Hiển thị lỗi nếu không tải được JComboBox
            JOptionPane.showMessageDialog(this, "Lỗi tải danh sách Hồ sơ/Bác sĩ: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void tblDonThuocMousePressed(java.awt.event.MouseEvent evt) {                                         
        int row = tblDonThuoc.getSelectedRow();
        
        if (row >= 0) {
            // Lấy dữ liệu từ TableModel
            String maHoSo = tableModel.getValueAt(row, 0).toString();
            String maDon = tableModel.getValueAt(row, 1).toString();
            String ngayKeDon = tableModel.getValueAt(row, 2).toString();
            String maBacSi = tableModel.getValueAt(row, 3).toString();
            
            // Đổ dữ liệu lên các ô nhập
            txtMaDon.setText(maDon);
            txtNgayKeDon.setText(ngayKeDon);
            comboMaHoSo.setSelectedItem(maHoSo);
            comboMaBacSi.setSelectedItem(maBacSi);
        }
    }
    
    public ManagePrescription() {
        initComponents();
        this.prescriptionController = new PrescriptionController();
        this.tableModel = (DefaultTableModel) tblDonThuoc.getModel();
        loadInitialData(); 
        loadTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboMaHoSo = new javax.swing.JComboBox<>();
        comboMaBacSi = new javax.swing.JComboBox<>();
        txtMaDon = new javax.swing.JTextField();
        txtNgayKeDon = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnHienThi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDonThuoc = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1360, 750));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(45, 55, 72));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mã Đơn");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mã Hồ Sơ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ngày kê đơn");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mã Bác Sĩ");

        comboMaHoSo.setBackground(new java.awt.Color(74, 85, 104));
        comboMaHoSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMaHoSoActionPerformed(evt);
            }
        });

        comboMaBacSi.setBackground(new java.awt.Color(74, 85, 104));
        comboMaBacSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMaBacSiActionPerformed(evt);
            }
        });

        txtMaDon.setBackground(new java.awt.Color(74, 85, 104));
        txtMaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaDonActionPerformed(evt);
            }
        });

        txtNgayKeDon.setBackground(new java.awt.Color(74, 85, 104));
        txtNgayKeDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayKeDonActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(56, 178, 172));
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(56, 178, 172));
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnHienThi.setBackground(new java.awt.Color(56, 178, 172));
        btnHienThi.setForeground(new java.awt.Color(255, 255, 255));
        btnHienThi.setText("Hiện thị");
        btnHienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiActionPerformed(evt);
            }
        });

        tblDonThuoc.setBackground(new java.awt.Color(74, 85, 104));
        tblDonThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Hồ Sơ", "Mã Đơn", "Ngày Kê Đơn", "Mã Bác Sĩ"
            }
        ));
        jScrollPane1.setViewportView(tblDonThuoc);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgayKeDon, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboMaHoSo, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaDon)
                            .addComponent(comboMaBacSi, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHienThi)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa))))
                .addContainerGap(129, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comboMaBacSi, comboMaHoSo, txtMaDon, txtNgayKeDon});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHienThi, btnThem, btnXoa});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboMaHoSo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(btnXoa))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtMaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addComponent(btnHienThi))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboMaBacSi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtNgayKeDon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comboMaBacSi, comboMaHoSo, txtMaDon, txtNgayKeDon});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnHienThi, btnThem, btnXoa});

        jTabbedPane2.addTab("Đơn Thuốc", jPanel2);

        jPanel1.setBackground(new java.awt.Color(45, 55, 72));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Chi Tiết Đơn Thuốc", jPanel1);

        add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void comboMaHoSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMaHoSoActionPerformed

        if (comboMaHoSo.getSelectedIndex() == -1 || comboMaHoSo.getSelectedItem() == null) {
            return; 
        }
        String selectedMaHoSo = (String) comboMaHoSo.getSelectedItem();

        try {
            String maBacSi = prescriptionController.getMaBacSiFromHoSo(selectedMaHoSo);
            if (maBacSi != null) {
                comboMaBacSi.setSelectedItem(maBacSi);
            } else {
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_comboMaHoSoActionPerformed

    private void comboMaBacSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMaBacSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMaBacSiActionPerformed

    private void txtMaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaDonActionPerformed

    private void txtNgayKeDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayKeDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayKeDonActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            String maDon = prescriptionController.nextPrescriptionID();
            String maHoSo = (String) comboMaHoSo.getSelectedItem();
            String maBacSi = (String) comboMaBacSi.getSelectedItem();
            java.util.Date ngayKeDon = new java.util.Date();

            if (maHoSo == null || maBacSi == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn Mã Hồ Sơ và Bác Sĩ.", "Thiếu thông tin", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            Prescription p = new Prescription(maHoSo, ngayKeDon, maBacSi);
            p.setMaDon(maDon);

            int kq = prescriptionController.insert(p);

            if (kq > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Thêm đơn thuốc thành công!", "Thành công", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
                loadTableData(); // Làm mới JTable
                clearForm();     // Chuẩn bị cho lần nhập tiếp theo
                
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Thêm thất bại. Mã đơn có thể đã tồn tại.", "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi khi thêm: " + e.getMessage(), "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int selectedRow = tblDonThuoc.getSelectedRow(); 
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn một đơn thuốc từ bảng để xóa.", "Chưa chọn", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String maDon = txtMaDon.getText(); 
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Bạn có chắc chắn muốn xóa đơn thuốc '" + maDon + "' không?", 
                "Xác nhận xóa", 
                javax.swing.JOptionPane.YES_NO_OPTION, 
                javax.swing.JOptionPane.WARNING_MESSAGE);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                int kq = prescriptionController.delete(maDon);
                if (kq > 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Xóa thành công!", "Thành công", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    loadTableData(); // Làm mới JTable
                    clearForm();     // Xóa trắng form
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Xóa thất bại. Không tìm thấy mã đơn.", "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Lỗi khi xóa: " + e.getMessage() + "\n(Có thể đơn thuốc này đã có chi tiết, bạn phải xóa chi tiết trước.)", "Lỗi CSDL", javax.swing.JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnHienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiActionPerformed
        try {
            loadTableData();
            clearForm();
            javax.swing.JOptionPane.showMessageDialog(this, "Đã làm mới dữ liệu.", "Thông báo", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi khi làm mới dữ liệu: " + e.getMessage(), "Lỗi", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnHienThiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHienThi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> comboMaBacSi;
    private javax.swing.JComboBox<String> comboMaHoSo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tblDonThuoc;
    private javax.swing.JTextField txtMaDon;
    private javax.swing.JTextField txtNgayKeDon;
    // End of variables declaration//GEN-END:variables
}
